/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import com.placeholder.PlaceHolder;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.TreeMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ASUS
 */
public class laporan extends javax.swing.JFrame {
    
    public Connection con;
    public Statement st;
    public ResultSet rs;
    DefaultTableModel model=new DefaultTableModel();
    String user = "root";
    String pswd = "";
    String host = "localhost";
    String db = "dbprimamotorsidomulyo";
    String url = "";
    private Connection Lconnection = null;
    private JTable table = null;

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
//        PlaceHolder holder1 = new PlaceHolder(txttanggaltransaksi, "Masukan Tanggal: YYYY/MM/DD");
        jTextField1.hide();
        jTextField1.requestFocus();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url = "jdbc:mysql://" + host + "/" + db + "?user=" + user
                    + "&password=" + pswd;
            Lconnection = DriverManager.getConnection(url);
        } catch (ClassNotFoundException e) {
            System.out.println("Driver tidak ditemukan");
        } catch (SQLException e) {
            System.out.println("koneksi gagal:" + e.toString());
        }
        
    }

    
    public final void subtotal () {
        String tanggal = txttanggaltransaksi.getText();
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
         try {
             Connection c=koneksi.getKoneksi();
             Statement s =c.createStatement();
             String sql="SELECT * FROM dbjualdetail WHERE time LIKE '%" + tanggal + "%'";
             ResultSet r = s.executeQuery(sql);
             while(r.next()){
               Object[]o=new Object[8];
               o[0]=r.getString("nofaktur");
               o[1]=r.getString("kodebarang");
               o[2]=r.getString("namabarang");
               o[3]=r.getString("harga");
               o[4]=r.getString("qty");
               o[5]=r.getString("subtotal");
               o[6]=r.getString("hargamodal");
               o[7]=r.getString("time");
               model.addRow(o);
             }
             r.close();
             s.close();
         } catch (SQLException e) {
             System.err.println("terjadi kesalahan");
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncetak = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        txttanggaltransaksi = new javax.swing.JTextField();
        home = new javax.swing.JLabel();
        transaksi = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncetakMouseClicked(evt);
            }
        });
        getContentPane().add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 740, 210, 45));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1560, 530));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 860, 40, -1));

        txttanggaltransaksi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txttanggaltransaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttanggaltransaksi.setText("YYYY-MM-DD");
        txttanggaltransaksi.setToolTipText("");
        txttanggaltransaksi.setBorder(null);
        txttanggaltransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggaltransaksiActionPerformed(evt);
            }
        });
        txttanggaltransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttanggaltransaksiKeyPressed(evt);
            }
        });
        getContentPane().add(txttanggaltransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 124, 790, 50));

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 8, 165, 54));

        transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        getContentPane().add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 8, 165, 54));

        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 8, 165, 54));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/laporan.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 900));
        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1619, 943));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttanggaltransaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttanggaltransaksiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
            subtotal();
            tampilTabel();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggaltransaksiKeyPressed

    private void txttanggaltransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggaltransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggaltransaksiActionPerformed

    //getdatadarijtabel
    private String getCellVal(int x, int y)
    {
        return model.getValueAt(x, y).toString();
    }
    //writetoexcel
    private void writetoexcel(){
        XSSFWorkbook wb=new XSSFWorkbook();
        XSSFSheet ws=wb.createSheet();
        
//        loaddata
            TreeMap<String,Object[]> data=new TreeMap<>();
            data.put("0", new Object[]{model.getColumnName(0),model.getColumnName(1),model.getColumnName(2),model.getColumnName(3),model.getColumnName(4),model.getColumnName(5),model.getColumnName(6),model.getColumnName(7)});
            data.put("1", new Object[]{getCellVal(0, 0),getCellVal(0, 1),getCellVal(0, 2),getCellVal(0, 3),getCellVal(0, 4),getCellVal(0, 5),getCellVal(0, 6),getCellVal(0, 7)});
            
            
    }
    
    public void export () {
    FileWriter fileWriter;

        JFileChooser chooser = new JFileChooser();

        chooser.setCurrentDirectory(new File(""));

        int retrival = chooser.showSaveDialog(null);

        if (retrival == JFileChooser.APPROVE_OPTION) {

            try{

                TableModel tModel = table.getModel();

                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));           

            // write header

                for(int i = 0; i < tModel.getColumnCount(); i++){

                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");

            }

                fileWriter.write("\n");

            // write record
                int jumlah = 0;
                int hargaModal = 0;

                for(int i=0; i < tModel.getRowCount(); i++) {

                for(int j=0; j < tModel.getColumnCount(); j++) {

                    fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
                    if (j == 6) {
                        jumlah += Integer.parseInt((String) tModel.getValueAt(i, j));
                    }
                    if (j == 7) {
                        hargaModal += Integer.parseInt((String) tModel.getValueAt(i, j));
                    }

                }
          

                    fileWriter.write("\n");

            }
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write(jumlah + "\t");
                fileWriter.write(hargaModal +"\t");
                fileWriter.write("\n");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("\t");
                fileWriter.write("Laba" + "\t");
                int laba = jumlah - hargaModal;
                fileWriter.write(+laba +"\t");

                fileWriter.close();

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);

            }

        }
}
    
    
    private void btncetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncetakMouseClicked
        export();

        // TODO add your handling code here:
    }//GEN-LAST:event_btncetakMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        new daftarbarang().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        new Transaksi().setVisible(true);
        dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_transaksiMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new loginkaryawan().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btncetak;
    private javax.swing.JLabel home;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel transaksi;
    private javax.swing.JTextField txttanggaltransaksi;
    // End of variables declaration//GEN-END:variables

    private Object[][] getData() {
        Object[][] data1 = null;
// String dari = datedari.getDateFormatString();
// String sampai = datesasmpai.getDateFormatString();
        String dari = txttanggaltransaksi.getText();
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM dbjualdetail WHERE time LIKE '%" + dari + "%'");
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();
            data1 = new Object[rowCount][8];
            int no = -1;
            while (rs.next()) {
                no = no + 1;
                data1[no][0] = rs.getString("time");
                data1[no][1] = rs.getString("nofaktur");
                data1[no][2] = rs.getString("kodebarang");
                data1[no][3] = rs.getString("namabarang");
                data1[no][4] = rs.getString("harga");
                data1[no][5] = rs.getString("qty");
                data1[no][6] = rs.getString("subtotal");
                data1[no][7] = rs.getString("hargamodal");

            }
            st.close();
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        } 
        return data1;
    }
    
private void tampilTabel() {
        String[] columnNames = {"tanggal", "nofaktur", "kodebarang", "namabarang", "harga", "qty", "subtotal", "hargamodal"};
        table = new JTable(getData(), columnNames);

        jScrollPane1.setViewportView(table);
    }
}
